name: ar_3d_viewer
description: A Flutter app to display 3D models in camera view for Android.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.7.2
  camera: ^0.10.5+9
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/models/Astronaut.glb
    - assets/models/hamburguesa.glb